const express = require('express');
const router = express.Router();
const stocksController = require('../controllers/stocksController');
const validateStock = require('../validators/validateStock');

router.get('/get-daily', stocksController.getDailyStocks);
router.get('/get-by-type', stocksController.getStocksByType);
router.get('/get-by-sort-type', stocksController.getUserStocks);
router.get('/get-types', stocksController.getStockTypes);
router.get('/get-indices', stocksController.getMajorIndexes);
router.get('/get-historical', stocksController.getHistoricalPrices);
router.get('/get-stock-historical', stocksController.getStockHistoricalPrices);
router.get('/get-stock-chart-data', stocksController.getStockChartData);
router.get('/get-user-stocks', stocksController.getUserStocks);
router.put('/update-user-stocks', validateStock.rules, stocksController.updateUserStocks);
router.put('/update-user-stocks-priority', validateStock.rules, stocksController.updateUserStocksPriority);
router.get('/search', stocksController.searchInStockTypeData);
router.get('/search-in-typed-stocks-data', stocksController.searchInStockTypeData);
router.get('/search-in-symbols-only', stocksController.searchStocksBySymbol);
router.get('/get-custom-stocks-chart-data', stocksController.getCustomStocksChartData);
router.get('/get-batch-results', stocksController.getBatchResults);
router.get('/get-graphs-data', stocksController.getStocksGraphData);
// router.get('/session/leave', usersController.leaveSession);
// router.get('/get-user-info', usersController.getUserInfo);
// router.post('/change-profile-image', uploadAvatar, usersController.changeAvatar);
// router.post('/change-cover-image', uploadCover, usersController.changeCover);
module.exports = router;
